const RegisterForms = {
  sellerIdForm: {
    key: 'sellerId',
    value: '',
    label: 'Seller ID',
    placeHolder: 'Seller ID',
    error: false,
    errorMessage: '*Pastikan Seller ID benar',
    regexPattern: /^\d{7}$/,
    keyboardType: 'phone-pad',
    inputType: 'text',
  },
  emailForm: {
    key: 'email',
    value: '',
    label: 'Email',
    title: 'contoh: user@pinjammodal.id',
    placeHolder: 'Masukan email kamu',
    error: false,
    errorMessage: '*Pastikan email kamu aktif',
    regexPattern:
      /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/,
    keyboardType: 'email-address',
    inputType: 'text',
  },
  passwordForm: {
    key: 'password',
    value: '',
    label: 'Kata Sandi',
    title: 'contoh: password123#',
    placeHolder: 'Masukan kata sandi',
    error: false,
    errorMessage: '*Kata sandi minimal 10 karakter',
    keyboardType: 'default',
    inputType: 'text',
    secureTextEntry: true,
  },
  fullNameForm: {
    key: 'fullName',
    value: '',
    label: 'Nama',
    title: 'contoh: User Pinjam Modal',
    placeHolder: 'Masukan nama kamu',
    error: false,
    errorMessage: '*Nama harus diisi',
    regexPattern: /.*/,
    keyboardType: 'default',
    inputType: 'text',
  },
  confirmPasswordForm: {
    key: 'confirmPassword',
    value: '',
    label: 'Konfirmasi Kata Sandi',
    title: 'contoh: password123#',
    placeHolder: 'Masukan konfirmasi kata sandi',
    error: false,
    errorMessage: '*Konfirmasi kata sandi harus sama dengan kata sandi',
    keyboardType: 'default',
    inputType: 'text',
    secureTextEntry: true,
  },
  phoneNumberForm: {
    key: 'phoneNumber',
    value: '',
    label: 'No. HP',
    title: 'contoh: 628123xxxxxxxx',
    placeHolder: 'Masukan nomor ponsel',
    error: false,
    errorMessage: 'Pastikan nomor ponsel benar',
    regexPattern: /^(\+62|62)?[\s-]?0?8[1-9]{1}\d{1}[\s-]?\d{4}[\s-]?\d{2,5}$/,
    keyboardType: 'phone-pad',
    inputType: 'phone-pad',
  },
}

export default RegisterForms;