const Strings = {
  infoPassword:
    'Kata sandi minimal 10 karakter terdiri dari huruf kecil dan besar, angka, dan spesial karakter.',
  footer: [
    {
      text: 'Dengan masuk dan daftar, saya menyetujui',
    },
    {
      text: ' persyaratan layanan ',
      link: 'https://www.pinjammodal.id/terms-and-conditions',
      title: 'Persyaratan Layanan',
    },
    {
      text: 'dan',
    },
    {
      text: ' kebijakan privasi ',
      link: 'https://www.pinjammodal.id/policy',
      title: 'Kebijakan Privasi',
    },
    {
      text: 'Pinjam Modal',
    },
  ],
  emailForm: {
    key: 'email',
    value: '',
    label: 'Email',
    title: 'contoh: user@pinjammodal.id',
    placeHolder: 'Masukan email kamu',
    error: false,
    errorMessage: '*Pastikan email kamu aktif',
    regexPattern:
      /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/,
    keyboardType: 'email-address',
    inputType: 'text',
  },
  passwordForm: {
    key: 'password',
    value: '',
    label: 'Kata Sandi',
    title: 'contoh: password123#',
    placeHolder: 'Masukan kata sandi',
    error: false,
    errorMessage: '*Kata sandi harus benar',
    keyboardType: 'default',
    inputType: 'text',
    secureTextEntry: true,
  },
  fullNameForm: {
    key: 'fullName',
    value: '',
    label: 'Nama',
    title: 'contoh: User Pinjam Modal',
    placeHolder: 'Masukan nama kamu',
    error: false,
    errorMessage: '*Nama harus diisi',
    regexPattern: /.*/,
    keyboardType: 'default',
    inputType: 'text',
  },
  confirmPasswordForm: {
    key: 'confirmPassword',
    value: '',
    label: 'Konfirmasi Kata Sandi',
    title: 'contoh: password123#',
    placeHolder: 'Masukan konfirmasi kata sandi',
    error: false,
    errorMessage: '*Konfirmasi kata sandi harus sama dengan kata sandi',
    keyboardType: 'default',
    inputType: 'text',
    secureTextEntry: true,
  },
  phoneNumberForm: {
    key: 'phoneNumber',
    value: '',
    label: 'No. HP',
    title: 'contoh: 628123xxxxxxxx',
    placeHolder: 'Masukan nomor ponsel',
    error: false,
    errorMessage: 'Pastikan nomor ponsel benar',
    regexPattern: /\+?([ -]?\d+)+|\(\d+\)([ -]\d+)/,
    keyboardType: 'phone-pad',
    inputType: 'phone-pad',
  },
  idCardNoForm: {
    key: 'phoneNumber',
    value: '',
    label: 'Nomor KTP',
    placeHolder: '',
    error: false,
    errorMessage: 'Pastikan nomor KTP benar',
    regexPattern: /^\\d{6}([04][1-9]|[1256][0-9]|[37][01])(0[1-9]|1[0-2])\d{2}\d{4}$/,
    keyboardType: 'phone-pad',
    inputType: 'phone-pad',
  },
  maidenNameForm: {
    key: 'maidenName',
    value: '',
    label: 'Nama Ibu Kandung',
    placeHolder: '',
    error: false,
    errorMessage: '*Nama harus diisi',
    regexPattern: /.*/,
    keyboardType: 'default',
    inputType: 'text',
  },
  birthplaceForm: {
    key: 'birthplace',
    value: '',
    label: 'Tempat Lahir',
    placeHolder: '',
    error: false,
    errorMessage: '*Tempat lahir harus diisi',
    regexPattern: /.*/,
    keyboardType: 'default',
    inputType: 'text',
  },
};

export default Strings;
